name: Workflow Name
# trigger
  # Define the event here

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # actions/checkout

      - name: Greeting Message
        # Write the command here
